name: Cloudsmith OIDC Auth

on:
    push:
        branches: [main]
env:
    CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
    CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
    id-token: write # Required for requesting the JWT
    contents: read # Required for actions/checkout

jobs:
    authenticate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Authenticate with Cloudsmith via OIDC
              uses: cloudsmith-io/cloudsmith-cli-action@v2
              with:
                  oidc-namespace: ${{env.CLOUDSMITH_NAMESPACE}}
                  oidc-service-slug: ${{env.CLOUDSMITH_SERVICE_SLUG}}
                  oidc-auth-only: "true"

            - name: Install Cloudsmith CLI
              uses: cloudsmith-io/cloudsmith-cli-action@v2
              with:
                  oidc-namespace: ${{env.CLOUDSMITH_NAMESPACE}}
                  oidc-service-slug: ${{env.CLOUDSMITH_SERVICE_SLUG}}

            - name: Verify Authentication
              run: |
                  cloudsmith whoami
