name: Cloudsmith OIDC Auth

on:
    push:
        branches: [main]

permissions:
    id-token: write # Required for requesting the JWT
    contents: read # Required for actions/checkout

jobs:
    authenticate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Authenticate with Cloudsmith via OIDC
              uses: cloudsmith-io/cloudsmith-cli-action@v1
              with:
                  # Your Cloudsmith Organization/Workspace name
                  oidc-namespace: "cloudsmith-org-neeraj"
                  # The slug of the service account created in Step 2A
                  oidc-service-slug: "github-actions-service-zz47"
                  # If true, it just sets the CLOUDSMITH_API_KEY env var
                  oidc-auth-only: "true"

            - name: Verify Authentication
              run: |
                  cloudsmith whoami
