name: Push Package to Cloudsmith

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # Mandatory for OIDC
  contents: read  # Required to checkout the repo

# Define these so the ${{ env.VARIABLE }} syntax works
env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  CLOUDSMITH_REPO_NAME: 'github-actions-assessment-repo'

jobs:
  push-to-cloudsmith:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v2
        with:
            oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
            oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Push package to Cloudsmith
        run: |
          cloudsmith push raw ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPO_NAME }} package.txt